language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script: gulp test
deploy:
  provider: heroku
  api_key:
    secure: NVtlz0xh1WIOgBi2K6rVuL3JSEAd0BQd9xq2CXqvwMkubeUqdFrjI794RPHYUN4C7mfGtq4XhlPSh3b1mTxB0Msl6LHNZPi+DJJtx00kxauFRSoaaVPI/zfGdepCOrZeSwoow++0PUZFsUm2Ca5xnWDpW7bbGTJlzKC9jZi7fTZS0Q004A/xAhBhIuvW3o5Dwvwo9CNrHAkms0dPq/MhBFPeilbwAGmSbnAQMxqIiBk6DlcoQwO6I7teEcEOXsTYJjzGxr4t0Li6sWqZ0Ng4tvQaEQv44h0Jui2qdLIf+sub5uAPheIbdmdcQeTxVsjllte3qmJQMnao5UtCSuCgAqO6QduktGhUgWJJTiLNOe4/EBgFiRgbgJw4T2THQlKi91sF+i96ITZ9IKcmfpEBNEyHTpjKQWze+cw4dXRO8ywrEC3i8Ev69/X3Vy4N4DmR2hG3qg5XqLMmw8yRm6K72Fz65pLCHdrJV8X/olhPy3jNv74zPblMrkYuFBmaNt2b3Sfcg3FverF1/83wUZoeiQPyKSyC48sLwVwJ97AiXP8h4fvMgKSeX3TEqhvbrqb1o0MvO+BSfMKb3LyjcZoVAOBwKfW5H6nMVnym5wplf4KglP3hMzpaamVXEe8uLP1t8fhwaeTqH/0UchpCiX1j8F8tPGvQigI8TAVsRgQ7sXw=
